###
 # @Description: 
 # @Author: zagger
 # @Date: 2021-03-20 11:31:27
 # @LastEditors: zagger
 # @LastEditTime: 2021-03-20 11:33:29
### 



source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/mappings.zsh

if [ -f ~/.sconfig/zsh/zshrc ]; then
	source ~/.sconfig/zsh/zshrc
fi

autopair-init
source ~/.zim/modules/fzf-tab/fzf-tab.plugin.zsh